# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  maven: circleci/maven@1.3.0
  codecov: codecov/codecov@3.2.3

workflows:
  maven_test:
    jobs:
      - maven/test
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
