# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  - store-jacoco:
      store_artifacts:
        path: target
  - run_mvn_test:
      maven/test


workflows:
  testing:
    jobs:
      - run_mvn_test
      - store-jacoco